# Generated by Django 6.0.7 on 2026-07-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=50, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ელ.ფოსტა')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='კურსის დასახელება')),
                ('description', models.TextField(blank=True, null=True, verbose_name='აღწერა')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main_app.lecturer', verbose_name='ლექტორი')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=50, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ელ.ფოსტა')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='რეგისტრაციის თარიღი')),
                ('courses', models.ManyToManyField(related_name='students', to='main_app.course', verbose_name='კურსები')),
            ],
        ),
    ]
